before:
  hooks:
    - go mod tidy
    - go mod download
builds:
  - id: kubectl-catalogd
    main: main.go
    binary: catalogd
    mod_timestamp: "{{ .CommitTimestamp }}"
    goos:
    - linux
    - darwin
    goarch:
    - amd64
    - arm64
    - ppc64le
    - s390x
release:
  disable: '{{ ne .Env.ENABLE_RELEASE_PIPELINE "true" }}'
changelog:
  use: github-native
  skip: '{{ ne .Env.ENABLE_RELEASE_PIPELINE "true" }}'
krews:
  - name: kubectl-catalogd
    description: kubectl plugin to interact with catalogd's HTTP server to fetch and view the contents of Catalog resources
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    commit_msg_template: "Krew plugin update for {{ .ProjectName }} version {{ .Tag }}"

