name: release

on:
  workflow_dispatch:
  merge_group:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:
    branches:
    - main

jobs:
  goreleaser:
    name: goreleaser
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install Go
      uses: actions/setup-go@v4
      with:
        go-version-file: "go.mod"

    - name: Set the release related variables
      run: |
        if [[ $GITHUB_REF == refs/tags/* ]]; then
          # Release tags.
          echo GORELEASER_ARGS="--clean" >> $GITHUB_ENV
          echo ENABLE_RELEASE_PIPELINE=true >> $GITHUB_ENV
        elif [[ $GITHUB_REF == refs/heads/* ]]; then
          # Branch build.
          echo GORELEASER_ARGS=" --snapshot --clean --skip=validate" >> $GITHUB_ENV
        fi

    - name: Run goreleaser
      run: make release
      env:
        GITHUB_TOKEN: ${{ github.token }}
        KREW_INDEX_TOKEN: ${{ secrets.KREW_INDEX_TOKEN }}